id: I83B3ABF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:34:46+00:00'
last_modified: '2022-06-09T07:30:54.719266+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1013
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF69:
      image_group_id: I1CZ2109
      title: Volume 1 of dwags po thar rgyan
      total_pages: 250
      order: 1
      base_file: AF69.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
