id: P007920
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1013
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  volumes:
    5efa9daaa43b46428321ce1495a0abf2:
      image_group_id: I1CZ2109
      title: ''
      volume_number: 1
      total_pages: 250
ebook_metadata:
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  sku: P007920
  cover: cover.jpg
  layers:
  - pagination
