id: P007920
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:49:15.345793
source_metadata:
  id: bdr:W1CZ1013
  title: དྭགས་པོ་ཐར་རྒྱན
  author: ''
  volumes:
    5105b34d51994594a5245aaf3ff0bf11:
      image_group_id: I1CZ2109
      title: Volume 1 of dwags po thar rgyan
      volume_number: 1
      total_pages: 250
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
